##############
# Site title
title: Michelle Viscaino
description: Personal and academic website
url: "https://michelleviscaino.com"  # Actualiza con tu dominio real

#########################
# Plugins & settings

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

collections:
  my_tags:
    output: true
    permalink: /tagged/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

permalink: /blog/:slug
timezone: America/New_York
future: false

# Excluded files/folders from build
exclude:
  - README.md
  - LICENSE.md
  - vendor

#########################
# Navigation bar links

nav:
  - name: "Home"
    link: "/"
  - name: "Teaching"
    link: "/teaching/"
  - name: "Research"
    link: "/research/"

#########################
# Optional special links (footer or extra)
special_links:
  # "Search": https://duckduckgo.com